# Generated by Django 3.0.2 on 2020-07-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='china',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='时间')),
                ('add_new', models.IntegerField(default=0, verbose_name='新增确诊人数')),
                ('sum_definite', models.IntegerField(default=0, verbose_name='总共确诊人数')),
                ('sum_suspected', models.IntegerField(default=0, verbose_name='总共确诊人数')),
            ],
        ),
    ]
