# Generated by Django 3.0.2 on 2020-07-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='时间')),
                ('add_new', models.IntegerField(default=0, verbose_name='新增确诊人数')),
                ('sum_definite', models.IntegerField(default=0, verbose_name='总共确诊人数')),
                ('sum_suspected', models.IntegerField(default=0, verbose_name='现有确诊人数')),
                ('sum_cure', models.IntegerField(default=0, verbose_name='总共治愈人数')),
                ('sum_die', models.IntegerField(default=0, verbose_name='总共死亡人数')),
                ('province_name', models.CharField(max_length=255, verbose_name='省份名称')),
                ('city_name', models.CharField(max_length=255, verbose_name='城市名字')),
            ],
        ),
    ]
