# Generated by Django 3.0.2 on 2020-07-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_province'),
    ]

    operations = [
        migrations.DeleteModel(
            name='anhui',
        ),
        migrations.DeleteModel(
            name='beijin',
        ),
        migrations.DeleteModel(
            name='chongqing',
        ),
        migrations.DeleteModel(
            name='fujian',
        ),
        migrations.DeleteModel(
            name='gansu',
        ),
        migrations.DeleteModel(
            name='guangdong',
        ),
        migrations.DeleteModel(
            name='guangxi',
        ),
        migrations.DeleteModel(
            name='guizhou',
        ),
        migrations.DeleteModel(
            name='hainan',
        ),
        migrations.DeleteModel(
            name='hebei',
        ),
        migrations.DeleteModel(
            name='heilongjiang',
        ),
        migrations.DeleteModel(
            name='henan',
        ),
        migrations.DeleteModel(
            name='hubei',
        ),
        migrations.DeleteModel(
            name='hunan',
        ),
        migrations.DeleteModel(
            name='jiangsu',
        ),
        migrations.DeleteModel(
            name='jiangxi',
        ),
        migrations.DeleteModel(
            name='jielin',
        ),
        migrations.DeleteModel(
            name='liaoning',
        ),
        migrations.DeleteModel(
            name='neimenggu',
        ),
        migrations.DeleteModel(
            name='ningxia',
        ),
        migrations.DeleteModel(
            name='qinghai',
        ),
        migrations.DeleteModel(
            name='sanxi',
        ),
        migrations.DeleteModel(
            name='shandong',
        ),
        migrations.DeleteModel(
            name='shanghai',
        ),
        migrations.DeleteModel(
            name='shanxi',
        ),
        migrations.DeleteModel(
            name='sichuan',
        ),
        migrations.DeleteModel(
            name='tianjing',
        ),
        migrations.DeleteModel(
            name='xinjiang',
        ),
        migrations.DeleteModel(
            name='xizang',
        ),
        migrations.DeleteModel(
            name='yunnan',
        ),
        migrations.DeleteModel(
            name='zejiang',
        ),
    ]
