# Generated by Django 3.0.2 on 2020-07-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20200723_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='china',
            name='province_name',
            field=models.CharField(default='', max_length=255, verbose_name='省份名称'),
        ),
        migrations.AlterField(
            model_name='china',
            name='sum_suspected',
            field=models.IntegerField(default=0, verbose_name='现有确诊人数'),
        ),
        migrations.AlterField(
            model_name='province',
            name='province_name',
            field=models.CharField(max_length=255, verbose_name='地区名称'),
        ),
        migrations.AlterField(
            model_name='province',
            name='sum_suspected',
            field=models.IntegerField(default=0, verbose_name='现有确诊人数'),
        ),
        migrations.AlterField(
            model_name='word',
            name='sum_suspected',
            field=models.IntegerField(default=0, verbose_name='现有确诊人数'),
        ),
    ]
