# Generated by Django 3.0.2 on 2020-07-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200723_1735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='province',
            new_name='guizhou',
        ),
    ]
